[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/full/path/to/node_modules/@vue/typescript-plugin"
languages = ["vue"]



[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
 
[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]


# go install golang.org/x/tools/gopls@latest
[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }


